# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflint" do
  desc "Pluggable Terraform linter"
  homepage "https://github.com/terraform-linters/tflint"
  version "0.64.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflint"

  on_macos do
    on_intel do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.64.0/tflint_darwin_amd64.zip"
      sha256 "0f3a9fd17526014646a2dfc3f9122f7b4161abe3d6b0f0f03f9014483ddf4d19"
    end
    on_arm do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.64.0/tflint_darwin_arm64.zip"
      sha256 "2496e9cb3d24992d553b45e7c87a0fdc9449ca975233876247a9bfeda857e6c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.64.0/tflint_linux_amd64.zip"
      sha256 "cca9d13e2e1d7a2c627af60ff899a3c9b74212899416aeb96ec764d2ef954537"
    end
    on_arm do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.64.0/tflint_linux_arm64.zip"
      sha256 "560da89aacf59389d4eb029730dd5b109b7288096c32f2726a0d9e783a5ea8eb"
    end
  end

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tflint"]
    end
  end

  # No zap stanza required
end
