# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflint" do
  desc "Pluggable Terraform linter"
  homepage "https://github.com/terraform-linters/tflint"
  version "0.63.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflint"

  on_macos do
    on_intel do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.63.1/tflint_darwin_amd64.zip"
      sha256 "1a22782473e4a01f0dd23edc649bed4420655a9e3459ffc06951e698eed7ad01"
    end
    on_arm do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.63.1/tflint_darwin_arm64.zip"
      sha256 "6aab157b22367dcab1635b370e98d6e791d9b40b021d4f9baef010d88f53e16b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.63.1/tflint_linux_amd64.zip"
      sha256 "8441a7d97df20431f19c9b9d27ff4c63e308c964e86660bc7cc0cf7bbe0725e8"
    end
    on_arm do
      url "https://github.com/terraform-linters/tflint/releases/download/v0.63.1/tflint_linux_arm64.zip"
      sha256 "6d858ca7f11858c3fe3c5e29cc746823abccb55e2d2e2da130fa7ad7ea4eecb8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflint"]
    end
  end

  # No zap stanza required
end
