# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflint" do
  version "0.62.1"

  on_macos do
    on_intel do
      sha256 "7f55df3a25deb610c267f600eb4247657e3ff776d0322916ceecd7b58142a73a"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_darwin_amd64.zip"
    end
    on_arm do
      sha256 "927866fef68382138b8fed038721a03c0928ce9486e1616b18bd3dd11e7cdacb"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "c004ec45ade3caf87cd4089feb1d2af9f7df57b13140a36df8a63c0a8cc69f14"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_linux_amd64.zip"
    end
    on_arm do
      sha256 "9f3bce43f7f58f05ddcf193f0bf1f7e7a9c7a79d7f46f72dd38e97f96fcaf14c"
      url "https://github.com/terraform-linters/tflint/releases/download/v#{version}/tflint_linux_arm64.zip"
    end
  end

  name "tflint"
  desc "Pluggable Terraform linter"
  homepage "https://github.com/terraform-linters/tflint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflint"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflint"]
    end
  end

  # No zap stanza required

end
